server:
  port: 7060

spring:
  application:
    name: cshop-auth
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.100:8848
    sentinel:
      transport:
        port: 8721
        dashboard: 192.168.56.100:8080


#Sentinel 适配了 Feign 组件。但默认是关闭的
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 120000

management:
  endpoints:
    web:
      exposure:
        include: "*"

# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug

business:
  oauth2:
    grant_type: password
    client_id: client
    client_secret: secret