stages:
  - build
  - run
  - clean

variables:
  DOCKER_HOST: tcp://192.168.56.100:2375

build:
  stage: build
  script:
    - mvn clean package dockerfile:build -Dmaven.test.skip=true

run:
  stage: run
  script:
    - docker-compose down
    - docker-compose up -d
clean:
  stage: clean
  script:
    - docker rmi $(docker images -q -f dangling=true)