version: '3.1'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 4070:8081
    volumes:
      - data:/nexus-data

volumes:
  data: