stages:
  - package
  - build
  - clean

variables:
  DOCKER_HOST: tcp://192.168.56.100:2375

package:
  stage: package
  script:
    - mvn clean package -Dmaven.test.skip=true

build:
  stage: build
  script:
    - cd cshop-basic
    - cd cshop-register && mvn dockerfile:build -Dmaven.test.skip=true && cd ..
    - cd cshop-config && mvn dockerfile:build -Dmaven.test.skip=true && cd ..
    - cd cshop-monitor && mvn dockerfile:build -Dmaven.test.skip=true && cd ..

#run:
#  stage: run
#  script:
#    - cd cshop-register && docker-compose down
#    - docker-compose up -d && cd ..

clean:
  stage: clean
  script:
    - docker rmi $(docker images -q -f dangling=true)