version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:6.4.3
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      cluster.name: elasticsearch
    volumes:
      - /data/docker/elasticsearch/data:/usr/share/elasticsearch/data
      - /data/docker/elasticsearch/plugins:/usr/share/elasticsearch/plugins