server:
  port: 7060

spring:
  application:
    name: cshop-auth-service
  freemarker:
    settings:
      number_format: 0.##########
    charset: UTF-8
    request-context-attribute: request
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

cshop:
  jwt:
    secret: cshop@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    publicKeyPath: /Users/june/share/rsa.pub # 公钥地址
    privateKeyPath: /Users/june/share/rsa.pri # 私钥地址
    expireMinutes: 30 # 过期时间,单位分钟
    cookieName: CS_TOKEN
    cookieMaxAge: 30