version: '3.1'
services:
  rancher:
    image: docker.io/rancher/server:latest　
    container_name: rancher
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    ports:
      - 5080:8080