version: '3.1'
services:
  jenkins:
    restart: always
    image: jenkinsci/jenkins
    container_name: jenkins
    ports:
      - 4090:8080
      - 4091:50000
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /data/docker/jenkins:/var/jenkins_home
