server:
  port: 8030


spring:
  application:
    name: cshop-order-service

  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.100:8848
    sentinel:
      transport:
        port: 7011
        dashboard: 192.168.56.100:7010

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://192.168.56.100:3306/orders?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      max-active: 30 #最大连接数
      min-idle: 5 #最小连接数
      max-wait: 10000 #获取连接的最大等待时间
      validation-query: select 'x'  #解决mysql 8小时问题
      time-between-eviction-runs-millis: 60000 #空闲连接检查时间间隔
      min-evictable-idle-time-millis: 300000 #空闲连接最小空闲时间

#Sentinel 适配了 Feign 组件。但默认是关闭的
feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

cshop:
  worker:
    workerId: 1
    dataCenterId: 1
  wxpay:
    appID: wx8397f8696b538317
    mchID: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    httpConnectTimeoutMs: 5000
    httpReadTimeoutMs: 10000