server:
  port: 7050
spring:
  application:
    name: cshop-image-service
  servlet:
    multipart:
      max-file-size: 10MB # 限制文件上传的大小
  cloud:
    ignoredInterfaces:  #禁用网卡
      - docker0
      - veth*
      - en0
      - br*
    nacos:
      discovery:
        server-addr: 192.168.56.100:8848

fdfs:
  so-timeout: 1501 #超时时间
  connect-timeout: 601 #连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 192.168.19.121:22122

management:
  endpoints:
    web:
      exposure:
        include: "*"