server:
  port: 7070

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: cshop-search-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.100:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.56.100:7010

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.56.100:9300
  rabbitmq:
    virtual-host: /cshop
    username: cshop
    password: cshop
    host: 192.168.56.100

#Sentinel 适配了 Feign 组件。但默认是关闭的
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 120000


management:
  endpoints:
    web:
      exposure:
        include: "*"
