server:
  port: 7070

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: cshop-search-service
  cloud:
    loadbalancer:
      retry:
        enabled: true
    inetutils:
      ignoredInterfaces:  #禁用网卡
        - docker0
        - veth.*
        - en0
    nacos:
      discovery:
        server-addr: 192.168.56.100:8848
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.56.100:9300
  rabbitmq:
    virtual-host: /cshop
    username: cshop
    password: cshop
    host: 192.168.56.100


management:
  endpoints:
    web:
      exposure:
        include: "*"
