server:
  port: 8020


spring:
  application:
    name: cshop-item-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.100:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.56.100:7010
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://192.168.56.100:3306/item?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      max-active: 30 #最大连接数
      min-idle: 5 #最小连接数
      max-wait: 10000 #获取连接的最大等待时间
      validation-query: select 'x'  #解决mysql 8小时问题
      time-between-eviction-runs-millis: 60000 #空闲连接检查时间间隔
      min-evictable-idle-time-millis: 300000 #空闲连接最小空闲时间


management:
  endpoints:
    web:
      exposure:
        include: "*"