server:
  port: 8040


spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值

  application:
    name: cshop-search-service

  data:
    elasticsearch:
      cluster-name: es-cluster
      cluster-nodes: 192.168.56.100:9300,192.168.56.100:9301
  rabbitmq:
    virtual-host: /cshop
    username: cshop
    password: cshop
    host: 192.168.56.100

  cloud:
    loadbalancer:
      retry:
        enabled: true

    inetutils:
      ignoredInterfaces:  #禁用网卡
        - docker0
        - veth.*
        - en0


  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}


ribbon:
  ConnectTimeout: 4000 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms



cshop:
  jwt:
    cookieName: CS_TOKEN
    publicKeyPath: /Users/june/share/rsa.pub # 公钥地址