server:
  port: 9999

spring:
  application:
    name: cshop-gateway
  cloud:
    inetutils:
      ignoredInterfaces:  #禁用网卡
        - docker0
        - veth.*
        - en0
  rabbitmq:
    virtual-host: /cshop
    username: cshop
    password: cshop
    host: 192.168.56.100

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

cshop:
  sms:
    accessKeyId: LTAIc259TULYzaS7
    accessKeySecret: 1uh79I1UAmwQ4YWsSmOgxw7JEBGA0v
    signName: CShop商城
    verifyCodeTemplate: SMS_148614415