version: '3.1'
services:
  cshop-config:
    restart: always
    image: 192.168.56.100:5000/cshop-config
    container_name: cshop-config
    environment:
      - EUREKA_INSTANCE_IP-ADDRESS=192.168.56.100
    ports:
      - 7000:7000
    networks:
      - cloud

# 创建自定义网络
networks:
  cloud:
    external:
      name: spring-cloud