version: '3.1'
services:
  gitlab:
    image: 'twang2218/gitlab-ce-zh'
    container_name: "gitlab"
    restart: always
    hostname: 'gitlab.javachen.com'
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.56.100:4080'
        gitlab_rails['gitlab_shell_ssh_port'] = 4022
        unicorn['port'] = 8888
        nginx['listen_port'] = 4080
    ports:
      - 4080:8080
      - 4081:22
    volumes:
      - /data/docker/gitlab/conf:/etc/gitlab
      - /data/docker/gitlab/data:/var/opt/gitlab
      - /data/docker/gitlab/logs:/var/log/gitlab
    extra_hosts:
      - "gitlab.javachen.com:192.168.56.100"