#### 整合freemarker
spring:
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path:
      - classpath:/templates
  application:
    name: eureka-javachen-portal-pay-web
  zipkin:
    base-url: http://127.0.0.1:9411/
    ###全部采集
  sleuth:
    sampler:
      probability: 1.0

#
#spring:
#  application:
#    name: eureka-itmayiedu-user


###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
server:
  port: 8050


 



