version: '3.1'
services:
  nexus:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: cshop
      RABBITMQ_DEFAULT_PASS: cshop
    ports:
      - 15672:15672
      - 5672:5672