server:
  port: 7040

spring:
  application:
    name: cshop-cache
  cloud:
    ignoredInterfaces:  #禁用网卡
      - docker0
      - veth*
      - en0
      - br*
    nacos:
      discovery:
        server-addr: 192.168.56.100:8848
  redis:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.10.151:26379, 192.168.10.151:26380, 192.168.10.151:26381
